# Generated by Django 4.2.7 on 2023-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.URLField(),
        ),
    ]
