# Generated by Django 4.2.7 on 2023-11-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_alter_images_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='id',
        ),
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
