# Generated by Django 4.2.7 on 2023-11-26 21:20

from django.db import migrations, models
import imageapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_remove_images_id_alter_images_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.URLField(primary_key=True, serialize=False, validators=[imageapp.models.validate_url]),
        ),
    ]
